#!/usr/bin/env python3
"""
============================================================
NAUKRI DHABA - SITEMAP GENERATOR
File: generate-sitemap.py
============================================================

Auto-generates sitemap.xml by scanning all HTML files.
Assigns SEO priorities based on page type.

USAGE:
  python3 generate-sitemap.py

RUN AUTOMATICALLY:
  Add to cron (runs daily at 2 AM):
  0 2 * * * cd /path/to/naukri-dhaba && python3 generate-sitemap.py
============================================================
"""

import glob
import os
from datetime import date, datetime

from site_config import PRETTY_ROUTE_MAP, SITE_URL

BASE_URL = SITE_URL
SITE_ROOT = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(SITE_ROOT, "sitemap.xml")

PAGE_RULES = {
    "index.html": {"priority": "1.0", "changefreq": "daily"},
    "latest-jobs.html": {"priority": "0.9", "changefreq": "daily"},
    "results.html": {"priority": "0.9", "changefreq": "daily"},
    "admit-cards.html": {"priority": "0.9", "changefreq": "daily"},
    "resources.html": {"priority": "0.7", "changefreq": "weekly"},
    "jobs/": {"priority": "0.8", "changefreq": "weekly"},
    "results/": {"priority": "0.8", "changefreq": "weekly"},
    "admit-cards/": {"priority": "0.8", "changefreq": "weekly"},
    "default": {"priority": "0.5", "changefreq": "monthly"},
}

EXCLUDE_PATTERNS = [
    "eligibility-calculator.html",
    "study-planner.html",
    "previous-papers.html",
    "go.html",
    "node_modules/",
    "staging/",
    "backup-main/",
    "share-diff-preview.html",
    "widget.html",
    "404.html",
]


def get_last_modified(filepath: str) -> str:
    mtime = os.path.getmtime(filepath)
    return datetime.fromtimestamp(mtime).strftime("%Y-%m-%d")


def get_page_rules(rel_path: str) -> dict[str, str]:
    filename = os.path.basename(rel_path)
    if filename in PAGE_RULES:
        return PAGE_RULES[filename]

    for prefix, rules in PAGE_RULES.items():
        if "/" in prefix and rel_path.startswith(prefix):
            return rules

    return PAGE_RULES["default"]


def should_exclude(rel_path: str) -> bool:
    return any(pattern in rel_path for pattern in EXCLUDE_PATTERNS)


def generate_sitemap() -> int:
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting sitemap generation...")
    print(f"Site root: {SITE_ROOT}")
    print(f"Base URL: {BASE_URL}")

    html_files: list[tuple[str, str]] = []
    for filepath in glob.iglob(os.path.join(SITE_ROOT, "**/*.html"), recursive=True):
        if ".git" in filepath:
            continue
        rel_path = os.path.relpath(filepath, SITE_ROOT).replace("\\", "/")
        if should_exclude(rel_path):
            continue
        html_files.append((rel_path, filepath))

    def sort_key(item: tuple[str, str]) -> tuple[int, str]:
        rel_path = item[0]
        if "/" not in rel_path:
            return (0, rel_path)
        if rel_path.startswith("jobs/"):
            return (1, rel_path)
        if rel_path.startswith("results/"):
            return (2, rel_path)
        if rel_path.startswith("admit-cards/"):
            return (3, rel_path)
        return (4, rel_path)

    html_files.sort(key=sort_key)

    today = date.today().strftime("%Y-%m-%d")
    xml_parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"',
        '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
        "",
        f"  <!-- Generated by Naukri Dhaba Sitemap Generator on {today} -->",
        f"  <!-- Total pages: {len(html_files)} -->",
        "",
    ]

    jobs_count = 0
    results_count = 0
    admits_count = 0
    root_count = 0

    for rel_path, filepath in html_files:
        if rel_path in PRETTY_ROUTE_MAP:
            url = f"{BASE_URL}{PRETTY_ROUTE_MAP[rel_path]}"
        else:
            url = f"{BASE_URL}/{rel_path}"

        lastmod = get_last_modified(filepath)
        rules = get_page_rules(rel_path)

        xml_parts.append("  <url>")
        xml_parts.append(f"    <loc>{url}</loc>")
        xml_parts.append(f"    <lastmod>{lastmod}</lastmod>")
        xml_parts.append(f"    <changefreq>{rules['changefreq']}</changefreq>")
        xml_parts.append(f"    <priority>{rules['priority']}</priority>")
        xml_parts.append("  </url>")
        xml_parts.append("")

        if rel_path.startswith("jobs/"):
            jobs_count += 1
        elif rel_path.startswith("results/"):
            results_count += 1
        elif rel_path.startswith("admit-cards/"):
            admits_count += 1
        else:
            root_count += 1

    xml_parts.append("</urlset>")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(xml_parts))

    print("\nSitemap generated successfully.")
    print(f"   Output: {OUTPUT_FILE}")
    print(f"   Total URLs: {len(html_files)}")
    print(f"   Root/Listing pages: {root_count}")
    print(f"   Job pages: {jobs_count}")
    print(f"   Result pages: {results_count}")
    print(f"   Admit Card pages: {admits_count}")
    print(f"   Last updated: {today}")

    # Ping search engines about updated sitemap
    ping_search_engines()

    return len(html_files)


def ping_search_engines() -> None:
    """Notify Google and Bing that the sitemap has been updated."""
    import urllib.request

    sitemap_url = f"{BASE_URL}/sitemap.xml"
    ping_urls = [
        f"https://www.google.com/ping?sitemap={sitemap_url}",
        f"https://www.bing.com/ping?sitemap={sitemap_url}",
    ]
    for url in ping_urls:
        try:
            req = urllib.request.Request(url, method="GET")
            with urllib.request.urlopen(req, timeout=10) as resp:
                print(f"   Pinged {url.split('?')[0].split('/')[-1]} → HTTP {resp.status}")
        except Exception as e:
            print(f"   Ping failed for {url}: {e}")


if __name__ == "__main__":
    generate_sitemap()
