"""Known official portals and full organisation names for recruiting bodies."""

from __future__ import annotations

import re

# Ordered: more specific keys first so 'UPSSSC' wins over 'SSC'.
BOARD_PORTALS: dict[str, str] = {
    "UPSSSC": "https://upsssc.gov.in",
    "UPPSC": "https://uppsc.up.nic.in",
    "UPSC": "https://upsc.gov.in",
    "SSC": "https://ssc.gov.in",
    "BPSC": "https://bpsc.bihar.gov.in",
    "BSSC": "https://bssc.bihar.gov.in",
    "BTSC": "https://btsc.bihar.gov.in",
    "CSBC": "https://csbc.bihar.gov.in",
    "BPSSC": "https://bpssc.bihar.gov.in",
    "MPPSC": "https://mppsc.mp.gov.in",
    "MPESB": "https://esb.mp.gov.in",
    "RPSC": "https://rpsc.rajasthan.gov.in",
    "RSMSSB": "https://rssb.rajasthan.gov.in",
    "RSSB": "https://rssb.rajasthan.gov.in",
    "JPSC": "https://www.jpsc.gov.in",
    "JSSC": "https://jssc.nic.in",
    "HSSC": "https://hssc.gov.in",
    "HPSC": "https://hpsc.gov.in",
    "HPPSC": "https://hppsc.hp.gov.in",
    "PPSC": "https://ppsc.gov.in",
    "GPSC": "https://gpsc.gujarat.gov.in",
    "MPSC": "https://mpsc.gov.in",
    "TNPSC": "https://www.tnpsc.gov.in",
    "KPSC": "https://kpsc.kar.nic.in",
    "OPSC": "https://www.opsc.gov.in",
    "OSSC": "https://www.ossc.gov.in",
    "CGPSC": "https://psc.cg.gov.in",
    "UKPSC": "https://psc.uk.gov.in",
    "UKSSSC": "https://sssc.uk.gov.in",
    "WBPSC": "https://wbpsc.gov.in",
    "APSC": "https://apsc.nic.in",
    "DSSSB": "https://dsssb.delhi.gov.in",
    "SBI": "https://sbi.co.in/web/careers",
    "IBPS": "https://www.ibps.in",
    "RBI": "https://opportunities.rbi.org.in",
    "NABARD": "https://www.nabard.org/careers",
    "LIC": "https://licindia.in/careers",
    "ECGC": "https://www.ecgc.in",
    "RRB": "https://www.rrbapply.gov.in",
    "RRC": "https://www.rrcb.gov.in",
    "DRDO": "https://rac.gov.in",
    "CISF": "https://cisfrectt.cisf.gov.in",
    "BSF": "https://rectt.bsf.gov.in",
    "CRPF": "https://rect.crpf.gov.in",
    "ITBP": "https://recruitment.itbpolice.nic.in",
    "AFCAT": "https://afcat.cdac.in",
    "HAL": "https://hal-india.co.in/careers",
    "INDIAN ARMY": "https://joinindianarmy.nic.in",
    "ARMY": "https://joinindianarmy.nic.in",
    "INDIAN NAVY": "https://www.joinindiannavy.gov.in",
    "NAVY": "https://www.joinindiannavy.gov.in",
    "AIR FORCE": "https://agnipathvayu.cdac.in",
    "AIRFORCE": "https://agnipathvayu.cdac.in",
    "COAST GUARD": "https://joinindiancoastguard.cdac.in",
    "ASSAM RIFLES": "https://assamrifles.gov.in",
    "CBSE": "https://www.cbse.gov.in",
    "CISCE": "https://www.cisce.org",
    "BSEB": "https://biharboardonline.bihar.gov.in",
    "BIHAR BOARD": "https://biharboardonline.bihar.gov.in",
    "BSEH": "https://bseh.org.in",
    "HBSE": "https://bseh.org.in",
    "CGBSE": "https://cgbse.nic.in",
    "JAC": "https://jac.jharkhand.gov.in",
    "MPBSE": "https://mpbse.nic.in",
    "MP BOARD": "https://mpbse.nic.in",
    "RBSE": "https://rajeduboard.rajasthan.gov.in",
    "UP BOARD": "https://upmsp.edu.in",
    "UPMSP": "https://upmsp.edu.in",
    "UBSE": "https://ubse.uk.gov.in",
    "NTA": "https://nta.ac.in",
    "CUET": "https://cuet.nta.nic.in",
    "JEE MAIN": "https://jeemain.nta.nic.in",
    "JEE ADVANCED": "https://jeeadv.ac.in",
    "NEET": "https://neet.nta.nic.in",
    "GATE": "https://gate.iitk.ac.in",
    "CTET": "https://ctet.nic.in",
    "CLAT": "https://consortiumofnlus.ac.in",
    "AIIMS": "https://aiimsexams.ac.in",
    "NORCET": "https://aiimsexams.ac.in",
    "BHU": "https://www.bhu.ac.in",
    "JEECUP": "https://jeecup.admissions.nic.in",
    "NVS": "https://navodaya.gov.in",
    "KVS": "https://kvsangathan.nic.in",
    "EMRS": "https://emrs.tribal.gov.in",
    "INDIA POST": "https://indiapostgdsonline.gov.in",
    "GDS": "https://indiapostgdsonline.gov.in",
    "IOCL": "https://iocl.com/latest-job-opening",
    "NCL": "https://www.nclcil.in",
    "COAL INDIA": "https://www.coalindia.in",
    "AAI": "https://www.aai.aero/en/careers/recruitment",
    "NTPC": "https://careers.ntpc.co.in",
    "ONGC": "https://ongcindia.com/web/eng/career",
    "BHEL": "https://careers.bhel.in",
    "SAIL": "https://sail.co.in/en/careers",
    "GAIL": "https://gailonline.com/CRcurrentopening.html",
    "ISRO": "https://www.isro.gov.in/Careers.html",
    "SUPREME COURT": "https://main.sci.gov.in",
    "PATNA HIGH COURT": "https://patnahighcourt.gov.in",
    "ALLAHABAD HIGH COURT": "https://www.allahabadhighcourt.in",
    "CSIR": "https://www.csir.res.in",
    "ESIC": "https://www.esic.gov.in",
    "NHM": "https://nhm.gov.in",
}

CATEGORY_PORTALS: dict[str, str] = {
    "upsc": "https://upsc.gov.in",
    "ssc": "https://ssc.gov.in",
    "railway": "https://www.rrbapply.gov.in",
    "banking": "https://www.ibps.in",
    "defence": "https://joinindianarmy.nic.in",
}

ORG_NAMES: dict[str, str] = {
    "UPSSSC": "Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)",
    "UPPSC": "Uttar Pradesh Public Service Commission (UPPSC)",
    "UPSC": "Union Public Service Commission (UPSC)",
    "SSC": "Staff Selection Commission (SSC)",
    "BPSC": "Bihar Public Service Commission (BPSC)",
    "BSSC": "Bihar Staff Selection Commission (BSSC)",
    "BTSC": "Bihar Technical Service Commission (BTSC)",
    "CSBC": "Central Selection Board of Constable, Bihar (CSBC)",
    "BPSSC": "Bihar Police Subordinate Services Commission (BPSSC)",
    "MPPSC": "Madhya Pradesh Public Service Commission (MPPSC)",
    "MPESB": "Madhya Pradesh Employees Selection Board (MPESB)",
    "RPSC": "Rajasthan Public Service Commission (RPSC)",
    "RSMSSB": "Rajasthan Staff Selection Board (RSMSSB)",
    "RSSB": "Rajasthan Staff Selection Board (RSSB)",
    "JPSC": "Jharkhand Public Service Commission (JPSC)",
    "JSSC": "Jharkhand Staff Selection Commission (JSSC)",
    "HSSC": "Haryana Staff Selection Commission (HSSC)",
    "HPSC": "Haryana Public Service Commission (HPSC)",
    "HPPSC": "Himachal Pradesh Public Service Commission (HPPSC)",
    "PPSC": "Punjab Public Service Commission (PPSC)",
    "GPSC": "Gujarat Public Service Commission (GPSC)",
    "MPSC": "Maharashtra Public Service Commission (MPSC)",
    "TNPSC": "Tamil Nadu Public Service Commission (TNPSC)",
    "KPSC": "Karnataka Public Service Commission (KPSC)",
    "OPSC": "Odisha Public Service Commission (OPSC)",
    "OSSC": "Odisha Staff Selection Commission (OSSC)",
    "CGPSC": "Chhattisgarh Public Service Commission (CGPSC)",
    "UKPSC": "Uttarakhand Public Service Commission (UKPSC)",
    "UKSSSC": "Uttarakhand Subordinate Service Selection Commission (UKSSSC)",
    "WBPSC": "West Bengal Public Service Commission (WBPSC)",
    "APSC": "Assam Public Service Commission (APSC)",
    "DSSSB": "Delhi Subordinate Services Selection Board (DSSSB)",
    "SBI": "State Bank of India (SBI)",
    "IBPS": "Institute of Banking Personnel Selection (IBPS)",
    "RBI": "Reserve Bank of India (RBI)",
    "NABARD": "National Bank for Agriculture and Rural Development (NABARD)",
    "LIC": "Life Insurance Corporation of India (LIC)",
    "RRB": "Railway Recruitment Board (RRB)",
    "RRC": "Railway Recruitment Cell (RRC)",
    "DRDO": "Defence Research and Development Organisation (DRDO)",
    "CISF": "Central Industrial Security Force (CISF)",
    "BSF": "Border Security Force (BSF)",
    "CRPF": "Central Reserve Police Force (CRPF)",
    "ITBP": "Indo-Tibetan Border Police (ITBP)",
    "HAL": "Hindustan Aeronautics Limited (HAL)",
    "INDIAN ARMY": "Indian Army",
    "INDIAN NAVY": "Indian Navy",
    "AIR FORCE": "Indian Air Force (IAF)",
    "COAST GUARD": "Indian Coast Guard",
    "CBSE": "Central Board of Secondary Education (CBSE)",
    "NTA": "National Testing Agency (NTA)",
    "AIIMS": "All India Institute of Medical Sciences (AIIMS)",
    "NVS": "Navodaya Vidyalaya Samiti (NVS)",
    "KVS": "Kendriya Vidyalaya Sangathan (KVS)",
    "EMRS": "Eklavya Model Residential Schools (EMRS)",
    "INDIA POST": "India Post",
    "IOCL": "Indian Oil Corporation Limited (IOCL)",
    "NTPC": "NTPC Limited",
    "ONGC": "Oil and Natural Gas Corporation (ONGC)",
    "BHEL": "Bharat Heavy Electricals Limited (BHEL)",
    "SAIL": "Steel Authority of India Limited (SAIL)",
    "GAIL": "GAIL (India) Limited",
    "ISRO": "Indian Space Research Organisation (ISRO)",
    "AAI": "Airports Authority of India (AAI)",
    "ESIC": "Employees' State Insurance Corporation (ESIC)",
    "NHM": "National Health Mission (NHM)",
    "UP BOARD": "Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)",
    "BIHAR BOARD": "Bihar School Examination Board (BSEB)",
}


def _find_key(text: str, table: dict[str, str]) -> str | None:
    tu = " " + re.sub(r"[^A-Z0-9 ]", " ", (text or "").upper()) + " "
    best: tuple[int, str] | None = None
    for key in table:
        if f" {key} " in tu:
            pos = tu.index(f" {key} ")
            if best is None or pos < best[0] or (pos == best[0] and len(key) > len(best[1])):
                best = (pos, key)
    return best[1] if best else None


def official_portal_for(title: str, dept: str = "", category: str = "") -> str:
    key = _find_key(f"{dept} {title}", BOARD_PORTALS)
    if key:
        return BOARD_PORTALS[key]
    return CATEGORY_PORTALS.get(category, "")


def full_org_name(title: str, dept: str = "") -> str:
    key = _find_key(f"{dept} {title}", ORG_NAMES)
    return ORG_NAMES[key] if key else ""
